<?php

namespace bl\BiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CorpsMetierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorpsMetierRepository extends EntityRepository
{
}
